# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

latex: false
fortran: false

matrix:
  include:
    - dist: xenial
    - os: osx
      brew_packages:
        - libpng
        - freetype
        - fontconfig

addons:
  apt:
    packages:
    - libpng16-dev
    
