# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

latex: false
fortran: false

matrix:
  include:
    - dist: xenial
      r_binary_packages: 
        - cairo
    - os: osx
      brew_packages:
        - libpng
        - freetype
        - fontconfig

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - gsfonts
      
